settings:
  title: 'Status Page'
  url: 'https://status-70726f.athemm.workers.dev' # used for Slack & Discord messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data yet'
  dayInHistogramNoData: 'No data yet'
  dayInHistogramOperational: 'Operational'
  dayInHistogramNotOperational: 'Some checks failed'

# list of monitors
monitors:
  - id: athemm-rocks # unique identifier
    name: athemm.rocks
    description: '' # default=empty
    url: 'https://www.athemm.rocks/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
